import {AbstractComponent, type TComponentConfig} from '@course/utils'
import css from './star-rating.module.css'
import flex from '@course/styles'
import cx from "@course/cx";


/**
 * Expected input:
 * {
 *   root: HTMLElement,
 *   className: string[],
 *   value: number,
 *   onValueChange: (value: number) => void,
 *   readOnly?: boolean
 * }
 *
 * Steps to complete:
 * 1. Init constructor - pass config with className, listeners
 * 2. Provide toHTML template - render star buttons with proper attributes
 * 3. Handle click event - update value and re-render
 * 4. Add afterRender - set ARIA attributes:
 *    Container:
 *    - role="radiogroup" — groups related radio-like controls so screen readers announce "radiogroup" when entering
 *    - aria-label="Star Rating" — provides an accessible name for the group (no visible label exists)
 *    - aria-readonly="true/false" — tells assistive tech whether the rating can be changed
 *    Each star button:
 *    - role="radio" — each star acts as a radio option within the group
 *    - aria-checked="true/false" — indicates which star is currently selected
 *    - aria-label="N Star(s)" — provides a meaningful label (e.g. "3 Stars") instead of just the emoji
 * 5. Add CSS styles for stars
 */

const STAR = '⭐️'
const STARS_COUNT = 5

type TStarRatingProps = {
  value: number,
  onValueChange?: (value: number) => void,
  readOnly?: boolean
}
export class StarRating extends AbstractComponent<TStarRatingProps> {

  value: number = 0;

  constructor(props: TComponentConfig<TStarRatingProps>) {
    // TODO: call super with config and listeners
    // TODO: init value from props
  }

  onClick({target}: Event) {
    // TODO: handle click event
    // - check if readOnly, return early if so
    // - check if target has data-rating attribute
    // - update value, call onValueChange, re-render
  }

  toHTML(): string {
    // TODO: return HTML template with:
    // - wrapper div with radiogroup role and flex layout
    // - hidden input with current value
    // - star buttons generated by getStar()
    return ''
  }

  getStar(index: number) {
    // TODO: return button HTML with:
    // - aria-checked, aria-label, role="radio"
    // - css.star class
    // - data-rating and data-checked attributes
    // - STAR emoji as content
    return ''
  }
}
